# Rozdíl uvedeného HDP na osobu s vypočítanou hodnotou podle populace

PREFIX country: <http://hrachjar.cz/country/#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/#>
PREFIX dbo: <http://dbpedia.org/ontology/#>
PREFIX economy: <http://hrachjar.cz/economy/#>

select ?name ?gdpPerCapita ?gdpPerCapita2 ?diff where {
  ?country a country:Country ;
    dbo:population ?population .
    ?country owl:sameAs ?economy .
    ?economy a economy:Economy ;
    foaf:name ?name ;
    economy:gdp ?gdp ;
    economy:gdpPerCapita ?gdpPerCapita .
    BIND((?gdp / ?population) AS ?gdpPerCapita2).
    BIND(abs(?gdpPerCapita - ?gdpPerCapita2) AS ?diff).
} order by ?diff