PREFIX country: <http://hrachjar.cz/country/#>
PREFIX economy: <http://hrachjar.cz/economy/#>
PREFIX gr:      <http://purl.org/goodrelations/v1#> 
PREFIX frapo: <http://purl.org/cerif/frapo/#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbo: <http://dbpedia.org/ontology/#>


CONSTRUCT {
    ?aUri a country:Country;
          foaf:name ?name;
          frapo:hasCountryCode ?code;
          dbo:capital ?capitalUri;
          gr:hasCurrency ?currency;
          dbo:area ?area;
          dbo:population ?population;
}
WHERE {
  BIND(IRI(CONCAT('http://hrachjar.cz/country/', 
    IF(STRSTARTS(?e, "AS"), "asia", 
      IF(STRSTARTS(?e, "NA"), "north-america", 
        IF(STRSTARTS(?e, "SA"), "south-america", 
          IF(STRSTARTS(?e, "EU"), "europe", 
            IF(STRSTARTS(?e, "AF"), "africa", 
              IF(STRSTARTS(?e, "OC"), "australia", "antarctica")))))), '/', LCASE(REPLACE(?l, " ", "-")))) AS ?aUri)
  BIND(xsd:string(?b) AS ?code)
  BIND(STRLANG(xsd:string(?l), "en") AS ?name)
  BIND(IRI(CONCAT('http://hrachjar.cz/country/', 
    IF(STRSTARTS(?e, "AS"), "asia", 
      IF(STRSTARTS(?e, "NA"), "north-america", 
        IF(STRSTARTS(?e, "SA"), "south-america", 
          IF(STRSTARTS(?e, "EU"), "europe", 
            IF(STRSTARTS(?e, "AF"), "africa", 
              IF(STRSTARTS(?e, "OC"), "australia", "antarctica")))))), '/', LCASE(REPLACE(?l, " ", "-")), '/', LCASE(REPLACE(REPLACE(REPLACE(?d, "\\'", ""), "\\.", ""), " ", "-") ) )) AS ?capitalUri)
  BIND(xsd:string(?f) AS ?currency)
  BIND(xsd:integer(?c) AS ?area)
  BIND(xsd:integer(?p) AS ?population)
}
OFFSET 1
