PREFIX country: <http://hrachjar.cz/country/#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbo: <http://dbpedia.org/ontology/#>

CONSTRUCT {
    ?aUri a country:Country;
          foaf:names ?names;
          dbo:capital ?capital;
          dbo:currency ?currency;
          dbo:area ?area;
          dbo:population ?population;
}
WHERE {
  BIND(IRI(CONCAT('http://hrachjar.cz/country/', 
    IF(STRSTARTS(?e, "AS"), "asia", 
      IF(STRSTARTS(?e, "NA"), "north-america", 
        IF(STRSTARTS(?e, "SA"), "south-america", 
          IF(STRSTARTS(?e, "EU"), "europe", 
            IF(STRSTARTS(?e, "AF"), "africa", "antarctica"))))), '/', LCASE(REPLACE(?l, " ", "-")))) AS ?aUri)
  BIND(STRLANG(xsd:string(?l), "en") AS ?names)
  BIND(STRLANG(xsd:string(?d), "en") AS ?capital)
  BIND(xsd:string(?e) AS ?currency)
  BIND(xsd:integer(?c) AS ?area)
  BIND(xsd:integer(?p) AS ?population)
}
OFFSET 1
